/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Grafica;

import Recursos.Portal;
import Recursos.Zonas;

/**
 *
 * @author rutos
 */
public class Ventan extends javax.swing.JFrame {
    private Zonas zonas;
    private Portal[] portales;
    /**
     * Creates new form Ventan
     */
    public Ventan(Zonas zonas, Portal[] portales) {
        this.zonas = zonas;
        this.portales=portales;
        initComponents();
        // Nuestro Timer para que se actualice solo cada 200 milisegundos
        javax.swing.Timer timer = new javax.swing.Timer(200, e -> actualizarDatos());
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCalle = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtByers = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtRadio = new javax.swing.JTextArea();
        labelSangre = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtPbos = new javax.swing.JTextArea();
        cruzabos = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtPbos2 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtPlab = new javax.swing.JTextArea();
        cruzalab = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        txtPlab2 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtPcen = new javax.swing.JTextArea();
        cruzacen = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtPcen2 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtPalc = new javax.swing.JTextArea();
        cruzaalc = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtPalc2 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        txtZbosN = new javax.swing.JTextArea();
        jScrollPane15 = new javax.swing.JScrollPane();
        txtZbosD = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        txtZlabN = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtZlabD = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane20 = new javax.swing.JScrollPane();
        txtZcenN = new javax.swing.JTextArea();
        jScrollPane17 = new javax.swing.JScrollPane();
        txtZcenD = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane18 = new javax.swing.JScrollPane();
        txtZalcN = new javax.swing.JTextArea();
        jScrollPane19 = new javax.swing.JScrollPane();
        txtZalcD = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        labelColmena = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 3, new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new java.awt.GridLayout(4, 4));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calle Principal");
        jPanel3.add(jLabel1);

        txtCalle.setColumns(20);
        txtCalle.setRows(5);
        jScrollPane1.setViewportView(txtCalle);

        jPanel3.add(jScrollPane1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sótano Byers");
        jPanel3.add(jLabel2);

        txtByers.setColumns(20);
        txtByers.setRows(5);
        jScrollPane2.setViewportView(txtByers);

        jPanel3.add(jScrollPane2);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Radio WSQK");
        jPanel3.add(jLabel3);

        txtRadio.setColumns(20);
        txtRadio.setRows(5);
        jScrollPane3.setViewportView(txtRadio);

        jPanel3.add(jScrollPane3);

        labelSangre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelSangre.setText("jLabel1");
        jPanel3.add(labelSangre);

        getContentPane().add(jPanel3);

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 3, 1, 3, new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new java.awt.GridLayout(4, 3));

        txtPbos.setColumns(20);
        txtPbos.setRows(5);
        jScrollPane5.setViewportView(txtPbos);

        jPanel2.add(jScrollPane5);

        cruzabos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cruzabos.setText("jLabel1");
        jPanel2.add(cruzabos);

        txtPbos2.setColumns(20);
        txtPbos2.setRows(5);
        jScrollPane6.setViewportView(txtPbos2);

        jPanel2.add(jScrollPane6);

        txtPlab.setColumns(20);
        txtPlab.setRows(5);
        jScrollPane7.setViewportView(txtPlab);

        jPanel2.add(jScrollPane7);

        cruzalab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cruzalab.setText("jLabel2");
        cruzalab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(cruzalab);

        txtPlab2.setColumns(20);
        txtPlab2.setRows(5);
        jScrollPane13.setViewportView(txtPlab2);

        jPanel2.add(jScrollPane13);

        txtPcen.setColumns(20);
        txtPcen.setRows(5);
        jScrollPane8.setViewportView(txtPcen);

        jPanel2.add(jScrollPane8);

        cruzacen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cruzacen.setText("jLabel3");
        jPanel2.add(cruzacen);

        txtPcen2.setColumns(20);
        txtPcen2.setRows(5);
        jScrollPane9.setViewportView(txtPcen2);

        jPanel2.add(jScrollPane9);

        txtPalc.setColumns(20);
        txtPalc.setRows(5);
        jScrollPane10.setViewportView(txtPalc);

        jPanel2.add(jScrollPane10);

        cruzaalc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cruzaalc.setText("jLabel4");
        jPanel2.add(cruzaalc);

        txtPalc2.setColumns(20);
        txtPalc2.setRows(5);
        jScrollPane12.setViewportView(txtPalc2);

        jPanel2.add(jScrollPane12);

        getContentPane().add(jPanel2);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 3, 1, 1, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.GridLayout(4, 3));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Bosque");
        jPanel1.add(jLabel4);

        txtZbosN.setColumns(20);
        txtZbosN.setRows(5);
        jScrollPane14.setViewportView(txtZbosN);

        jPanel1.add(jScrollPane14);

        txtZbosD.setColumns(20);
        txtZbosD.setRows(5);
        jScrollPane15.setViewportView(txtZbosD);

        jPanel1.add(jScrollPane15);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Laboratorio");
        jPanel1.add(jLabel5);

        txtZlabN.setColumns(20);
        txtZlabN.setRows(5);
        jScrollPane16.setViewportView(txtZlabN);

        jPanel1.add(jScrollPane16);

        txtZlabD.setColumns(20);
        txtZlabD.setRows(5);
        jScrollPane11.setViewportView(txtZlabD);

        jPanel1.add(jScrollPane11);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Centro Comercial");
        jPanel1.add(jLabel6);

        txtZcenN.setColumns(20);
        txtZcenN.setRows(5);
        jScrollPane20.setViewportView(txtZcenN);

        jPanel1.add(jScrollPane20);

        txtZcenD.setColumns(20);
        txtZcenD.setRows(5);
        jScrollPane17.setViewportView(txtZcenD);

        jPanel1.add(jScrollPane17);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Alcantarillado");
        jPanel1.add(jLabel7);

        txtZalcN.setColumns(20);
        txtZalcN.setRows(5);
        jScrollPane18.setViewportView(txtZalcN);

        jPanel1.add(jScrollPane18);

        txtZalcD.setColumns(20);
        txtZalcD.setRows(5);
        jScrollPane19.setViewportView(txtZalcD);

        jPanel1.add(jScrollPane19);

        getContentPane().add(jPanel1);

        jPanel7.setLayout(new java.awt.GridLayout(2, 1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Colmena");
        jPanel7.add(jLabel8);

        labelColmena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelColmena.setText("jLabel1");
        jPanel7.add(labelColmena);

        getContentPane().add(jPanel7);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cruzaalc;
    private javax.swing.JLabel cruzabos;
    private javax.swing.JLabel cruzacen;
    private javax.swing.JLabel cruzalab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelColmena;
    private javax.swing.JLabel labelSangre;
    private javax.swing.JTextArea txtByers;
    private javax.swing.JTextArea txtCalle;
    private javax.swing.JTextArea txtPalc;
    private javax.swing.JTextArea txtPalc2;
    private javax.swing.JTextArea txtPbos;
    private javax.swing.JTextArea txtPbos2;
    private javax.swing.JTextArea txtPcen;
    private javax.swing.JTextArea txtPcen2;
    private javax.swing.JTextArea txtPlab;
    private javax.swing.JTextArea txtPlab2;
    private javax.swing.JTextArea txtRadio;
    private javax.swing.JTextArea txtZalcD;
    private javax.swing.JTextArea txtZalcN;
    private javax.swing.JTextArea txtZbosD;
    private javax.swing.JTextArea txtZbosN;
    private javax.swing.JTextArea txtZcenD;
    private javax.swing.JTextArea txtZcenN;
    private javax.swing.JTextArea txtZlabD;
    private javax.swing.JTextArea txtZlabN;
    // End of variables declaration//GEN-END:variables
    private void actualizarDatos() {
    if (zonas != null) {
        
        txtCalle.setText(zonas.getCallePrincipalTexto());
        txtByers.setText(zonas.getSotanoByersTexto());
        txtRadio.setText(zonas.getRadioWSQKTexto());
        labelSangre.setText("SANGRE RECOLECTADA: " + zonas.getSangreDisponible());
        //Índices: 0=Bosque, 1=Lab, 2=Centro, 3=Alcantarillado
        //portales
        //ida (esperando)
        txtPbos.setText(portales[0].getIdaTexto());
        txtPlab.setText(portales[1].getIdaTexto());
        txtPcen.setText(portales[2].getIdaTexto());
        txtPalc.setText(portales[3].getIdaTexto());
        //vuelta(esperando)
        txtPbos2.setText(portales[0].getVueltaTexto());
        txtPlab2.setText(portales[1].getVueltaTexto());
        txtPcen2.setText(portales[2].getVueltaTexto());
        txtPalc2.setText(portales[3].getVueltaTexto());
        //cruzando
        cruzabos.setText(portales[0].getNinoCruzando());
        cruzalab.setText(portales[1].getNinoCruzando());
        cruzacen.setText(portales[2].getNinoCruzando());
        cruzaalc.setText(portales[3].getNinoCruzando());
        //Zonas. 
        txtZbosN.setText(zonas.getNinosEnZonaUpsideDown(0));
        txtZbosD.setText(zonas.getDemosEnZonaUpsideDown(0));
        txtZlabN.setText(zonas.getNinosEnZonaUpsideDown(1));
        txtZlabD.setText(zonas.getDemosEnZonaUpsideDown(1));
        txtZcenN.setText(zonas.getNinosEnZonaUpsideDown(2));
        txtZcenD.setText(zonas.getDemosEnZonaUpsideDown(2));
        txtZalcN.setText(zonas.getNinosEnZonaUpsideDown(3));
        txtZalcD.setText(zonas.getDemosEnZonaUpsideDown(3));
        
        
        labelColmena.setText("Niños: "+zonas.getNinosEnColmena());
    }
}



}
